### ISSUE TITLE
Add Vite ("package.json is only for eslint")

### ISSUE THREAD

**Issue by pedropcamellon** [electricg/period-tracker#1]
Hi! Have you considered adding Webpack, Vite, Bun or any other bundler? Vite is pretty fast and comes with a dev server. 
I think this is an awesome project and I want to help. I know a little of UX/UI design, JS, html y css.

**Comment by electricg** [comment]
Thank you, but the code is vanilla javascript and doesn't need any builder or similar, and it runs on any static server. This is all on purpose.

As this is a personal pet project of mine, I am just keeping as it is. Feel free to fork it and do whatever you want with it.

**Comment by pedropcamellon** [comment]
I understand. Thank you!
